
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xeq.h"

/*
* The configuration table for devices
*/

XEq_Config XEq_ConfigTable[XPAR_XEQ_NUM_INSTANCES] =
{
	{
		XPAR_EQ_0_DEVICE_ID,
		XPAR_EQ_0_S_AXI_CTRL_BASEADDR
	}
};


