// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module EQ_fft (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buf_re_address0,
        buf_re_ce0,
        buf_re_we0,
        buf_re_d0,
        buf_re_q0,
        buf_re_address1,
        buf_re_ce1,
        buf_re_q1,
        buf_im_address0,
        buf_im_ce0,
        buf_im_we0,
        buf_im_d0,
        buf_im_q0,
        buf_im_address1,
        buf_im_ce1,
        buf_im_q1,
        fft_size,
        inverse_offset
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_state2 = 18'd2;
parameter    ap_ST_fsm_state3 = 18'd4;
parameter    ap_ST_fsm_state4 = 18'd8;
parameter    ap_ST_fsm_state5 = 18'd16;
parameter    ap_ST_fsm_state6 = 18'd32;
parameter    ap_ST_fsm_state7 = 18'd64;
parameter    ap_ST_fsm_state8 = 18'd128;
parameter    ap_ST_fsm_state9 = 18'd256;
parameter    ap_ST_fsm_state10 = 18'd512;
parameter    ap_ST_fsm_state11 = 18'd1024;
parameter    ap_ST_fsm_state12 = 18'd2048;
parameter    ap_ST_fsm_state13 = 18'd4096;
parameter    ap_ST_fsm_state14 = 18'd8192;
parameter    ap_ST_fsm_state15 = 18'd16384;
parameter    ap_ST_fsm_state16 = 18'd32768;
parameter    ap_ST_fsm_state17 = 18'd65536;
parameter    ap_ST_fsm_state18 = 18'd131072;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] buf_re_address0;
output   buf_re_ce0;
output   buf_re_we0;
output  [39:0] buf_re_d0;
input  [39:0] buf_re_q0;
output  [9:0] buf_re_address1;
output   buf_re_ce1;
input  [39:0] buf_re_q1;
output  [9:0] buf_im_address0;
output   buf_im_ce0;
output   buf_im_we0;
output  [39:0] buf_im_d0;
input  [39:0] buf_im_q0;
output  [9:0] buf_im_address1;
output   buf_im_ce1;
input  [39:0] buf_im_q1;
input  [10:0] fft_size;
input   inverse_offset;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[9:0] buf_re_address0;
reg buf_re_ce0;
reg buf_re_we0;
reg[39:0] buf_re_d0;
reg buf_re_ce1;
reg[9:0] buf_im_address0;
reg buf_im_ce0;
reg buf_im_we0;
reg[39:0] buf_im_d0;
reg buf_im_ce1;

(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [8:0] twiddle_re_V_address0;
reg    twiddle_re_V_ce0;
reg    twiddle_re_V_we0;
wire   [23:0] twiddle_re_V_q0;
reg   [8:0] twiddle_im_V_address0;
reg    twiddle_im_V_ce0;
reg    twiddle_im_V_we0;
wire   [23:0] twiddle_im_V_q0;
reg  signed [39:0] reg_297;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state15;
reg  signed [39:0] reg_301;
wire   [0:0] inverse_offset_read_read_fu_102_p2;
wire   [31:0] fft_size_cast_fu_310_p1;
reg   [31:0] fft_size_cast_reg_629;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln53_fu_319_p1;
reg   [63:0] zext_ln53_reg_640;
wire   [10:0] add_ln53_fu_330_p2;
reg   [10:0] add_ln53_reg_651;
wire    ap_CS_fsm_state4;
wire   [9:0] empty_54_fu_336_p1;
reg   [9:0] empty_54_reg_656;
wire   [0:0] icmp_ln53_fu_325_p2;
wire   [0:0] icmp_ln63_fu_341_p2;
reg   [0:0] icmp_ln63_reg_661;
wire   [0:0] icmp_ln55_fu_368_p2;
reg   [0:0] icmp_ln55_reg_672;
wire    ap_CS_fsm_state6;
reg   [9:0] buf_re_addr_reg_676;
reg   [9:0] buf_im_addr_reg_681;
reg   [9:0] buf_re_addr_1_reg_686;
reg   [9:0] buf_im_addr_1_reg_691;
reg   [9:0] trunc_ln8_reg_702;
wire    ap_CS_fsm_state9;
wire   [0:0] icmp_ln63_1_fu_381_p2;
wire  signed [63:0] sext_ln66_fu_412_p1;
reg  signed [63:0] sext_ln66_reg_707;
wire  signed [31:0] sext_ln66_1_fu_416_p1;
reg  signed [31:0] sext_ln66_1_reg_712;
wire   [8:0] empty_55_fu_425_p1;
reg   [8:0] empty_55_reg_717;
wire   [9:0] trunc_ln66_fu_434_p1;
reg   [9:0] trunc_ln66_reg_725;
wire    ap_CS_fsm_state10;
wire   [0:0] icmp_ln66_fu_429_p2;
wire   [31:0] add_ln68_fu_457_p2;
reg   [31:0] add_ln68_reg_733;
wire    ap_CS_fsm_state11;
wire   [8:0] add_ln69_fu_463_p2;
reg   [8:0] add_ln69_reg_738;
wire   [0:0] icmp_ln68_fu_452_p2;
wire   [9:0] add_ln73_fu_474_p2;
reg   [9:0] add_ln73_reg_753;
reg   [9:0] buf_re_addr_2_reg_758;
reg   [9:0] buf_im_addr_2_reg_763;
wire   [63:0] add_ln66_fu_490_p2;
reg   [23:0] tr_V_reg_773;
reg   [23:0] ti_V_reg_778;
wire  signed [61:0] sext_ln1316_fu_495_p1;
wire    ap_CS_fsm_state13;
wire  signed [61:0] sext_ln1319_fu_499_p1;
wire  signed [61:0] sext_ln1316_1_fu_508_p1;
wire  signed [61:0] sext_ln1319_1_fu_512_p1;
wire   [61:0] grp_fu_502_p2;
reg   [61:0] r_V_17_reg_807;
wire    ap_CS_fsm_state14;
wire   [61:0] grp_fu_515_p2;
reg   [61:0] r_V_19_reg_812;
wire   [61:0] grp_fu_521_p2;
reg   [61:0] r_V_20_reg_817;
wire   [61:0] grp_fu_527_p2;
reg   [61:0] r_V_21_reg_822;
reg   [9:0] buf_re_addr_3_reg_827;
reg   [9:0] buf_im_addr_3_reg_832;
reg   [39:0] pr_V_reg_837;
reg   [39:0] pi_V_reg_843;
wire   [39:0] sub_ln859_fu_578_p2;
reg   [39:0] sub_ln859_reg_849;
wire    ap_CS_fsm_state16;
wire   [39:0] sub_ln859_1_fu_583_p2;
reg   [39:0] sub_ln859_1_reg_854;
wire    grp_init_twiddle_fu_248_ap_start;
wire    grp_init_twiddle_fu_248_ap_done;
wire    grp_init_twiddle_fu_248_ap_idle;
wire    grp_init_twiddle_fu_248_ap_ready;
wire   [8:0] grp_init_twiddle_fu_248_twiddle_re_V_address0;
wire    grp_init_twiddle_fu_248_twiddle_re_V_ce0;
wire    grp_init_twiddle_fu_248_twiddle_re_V_we0;
wire   [23:0] grp_init_twiddle_fu_248_twiddle_re_V_d0;
wire   [8:0] grp_init_twiddle_fu_248_twiddle_im_V_address0;
wire    grp_init_twiddle_fu_248_twiddle_im_V_ce0;
wire    grp_init_twiddle_fu_248_twiddle_im_V_we0;
wire   [23:0] grp_init_twiddle_fu_248_twiddle_im_V_d0;
wire    grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_ap_start;
wire    grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_ap_done;
wire    grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_ap_idle;
wire    grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_ap_ready;
wire   [31:0] grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_logN_out;
wire    grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_logN_out_ap_vld;
wire   [31:0] grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_logN_1_out;
wire    grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_logN_1_out_ap_vld;
wire    grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_ap_start;
wire    grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_ap_done;
wire    grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_ap_idle;
wire    grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_ap_ready;
wire   [31:0] grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_n_out;
wire    grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_n_out_ap_vld;
wire    grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_ap_start;
wire    grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_ap_done;
wire    grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_ap_idle;
wire    grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_ap_ready;
wire   [9:0] grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_re_address0;
wire    grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_re_ce0;
wire    grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_re_we0;
wire   [39:0] grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_re_d0;
wire   [9:0] grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_re_address1;
wire    grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_re_ce1;
wire   [9:0] grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_im_address0;
wire    grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_im_ce0;
wire    grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_im_we0;
wire   [39:0] grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_im_d0;
wire   [9:0] grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_im_address1;
wire    grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_im_ce1;
reg   [63:0] k_reg_214;
reg   [31:0] j_reg_226;
wire    ap_CS_fsm_state17;
reg   [8:0] phi_mul_reg_237;
reg    grp_init_twiddle_fu_248_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_ap_start_reg;
reg   [31:0] logN_1_loc_fu_90;
reg    grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_ap_start_reg;
wire    ap_CS_fsm_state18;
wire   [63:0] zext_ln53_1_fu_351_p1;
wire   [63:0] zext_ln55_fu_362_p1;
wire   [63:0] zext_ln70_fu_468_p1;
wire   [63:0] zext_ln73_1_fu_484_p1;
wire   [63:0] zext_ln73_fu_533_p1;
reg   [10:0] i_1_fu_82;
wire    ap_CS_fsm_state8;
reg   [31:0] s_fu_98;
wire   [31:0] s_3_fu_438_p2;
wire    ap_CS_fsm_state7;
wire   [39:0] add_ln859_fu_566_p2;
wire   [39:0] add_ln859_1_fu_572_p2;
wire   [31:0] zext_ln53_2_fu_356_p1;
wire  signed [31:0] m_fu_386_p2;
wire   [30:0] m2_fu_392_p4;
wire   [31:0] p_lshr_f_fu_420_p2;
wire   [9:0] trunc_ln68_fu_448_p1;
wire   [9:0] add_ln73_1_fu_479_p2;
wire  signed [39:0] grp_fu_502_p0;
wire  signed [23:0] grp_fu_502_p1;
wire  signed [39:0] grp_fu_515_p0;
wire  signed [23:0] grp_fu_515_p1;
wire  signed [39:0] grp_fu_521_p0;
wire  signed [23:0] grp_fu_521_p1;
wire  signed [39:0] grp_fu_527_p0;
wire  signed [23:0] grp_fu_527_p1;
wire   [61:0] ret_V_fu_538_p2;
wire   [61:0] ret_V_9_fu_552_p2;
wire   [39:0] add_ln859_fu_566_p0;
wire   [39:0] add_ln859_1_fu_572_p0;
wire   [39:0] sub_ln859_fu_578_p0;
wire   [39:0] sub_ln859_1_fu_583_p0;
reg    ap_block_state18_on_subcall_done;
reg   [17:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 18'd1;
#0 grp_init_twiddle_fu_248_ap_start_reg = 1'b0;
#0 grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_ap_start_reg = 1'b0;
#0 grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_ap_start_reg = 1'b0;
#0 grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_ap_start_reg = 1'b0;
end

EQ_fft_twiddle_re_V_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
twiddle_re_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(twiddle_re_V_address0),
    .ce0(twiddle_re_V_ce0),
    .we0(twiddle_re_V_we0),
    .d0(grp_init_twiddle_fu_248_twiddle_re_V_d0),
    .q0(twiddle_re_V_q0)
);

EQ_fft_twiddle_re_V_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
twiddle_im_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(twiddle_im_V_address0),
    .ce0(twiddle_im_V_ce0),
    .we0(twiddle_im_V_we0),
    .d0(grp_init_twiddle_fu_248_twiddle_im_V_d0),
    .q0(twiddle_im_V_q0)
);

EQ_init_twiddle grp_init_twiddle_fu_248(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_init_twiddle_fu_248_ap_start),
    .ap_done(grp_init_twiddle_fu_248_ap_done),
    .ap_idle(grp_init_twiddle_fu_248_ap_idle),
    .ap_ready(grp_init_twiddle_fu_248_ap_ready),
    .fft_size(fft_size),
    .inverse(inverse_offset),
    .twiddle_re_V_address0(grp_init_twiddle_fu_248_twiddle_re_V_address0),
    .twiddle_re_V_ce0(grp_init_twiddle_fu_248_twiddle_re_V_ce0),
    .twiddle_re_V_we0(grp_init_twiddle_fu_248_twiddle_re_V_we0),
    .twiddle_re_V_d0(grp_init_twiddle_fu_248_twiddle_re_V_d0),
    .twiddle_im_V_address0(grp_init_twiddle_fu_248_twiddle_im_V_address0),
    .twiddle_im_V_ce0(grp_init_twiddle_fu_248_twiddle_im_V_ce0),
    .twiddle_im_V_we0(grp_init_twiddle_fu_248_twiddle_im_V_we0),
    .twiddle_im_V_d0(grp_init_twiddle_fu_248_twiddle_im_V_d0)
);

EQ_fft_Pipeline_VITIS_LOOP_50_1 grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_ap_start),
    .ap_done(grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_ap_done),
    .ap_idle(grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_ap_idle),
    .ap_ready(grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_ap_ready),
    .fft_size(fft_size),
    .logN_out(grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_logN_out),
    .logN_out_ap_vld(grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_logN_out_ap_vld),
    .logN_1_out(grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_logN_1_out),
    .logN_1_out_ap_vld(grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_logN_1_out_ap_vld)
);

EQ_fft_Pipeline_VITIS_LOOP_38_1 grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_ap_start),
    .ap_done(grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_ap_done),
    .ap_idle(grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_ap_idle),
    .ap_ready(grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_ap_ready),
    .logN_reload(grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_logN_out),
    .i_4_cast_cast(empty_54_reg_656),
    .n_out(grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_n_out),
    .n_out_ap_vld(grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_n_out_ap_vld)
);

EQ_fft_Pipeline_VITIS_LOOP_90_6 grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_ap_start),
    .ap_done(grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_ap_done),
    .ap_idle(grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_ap_idle),
    .ap_ready(grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_ap_ready),
    .fft_size(fft_size),
    .buf_re_address0(grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_re_address0),
    .buf_re_ce0(grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_re_ce0),
    .buf_re_we0(grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_re_we0),
    .buf_re_d0(grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_re_d0),
    .buf_re_address1(grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_re_address1),
    .buf_re_ce1(grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_re_ce1),
    .buf_re_q1(buf_re_q1),
    .conv_i_i_i28(fft_size),
    .buf_im_address0(grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_im_address0),
    .buf_im_ce0(grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_im_ce0),
    .buf_im_we0(grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_im_we0),
    .buf_im_d0(grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_im_d0),
    .buf_im_address1(grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_im_address1),
    .buf_im_ce1(grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_im_ce1),
    .buf_im_q1(buf_im_q1)
);

EQ_mul_40s_24s_62_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 62 ))
mul_40s_24s_62_2_1_U64(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_502_p0),
    .din1(grp_fu_502_p1),
    .ce(1'b1),
    .dout(grp_fu_502_p2)
);

EQ_mul_40s_24s_62_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 62 ))
mul_40s_24s_62_2_1_U65(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_515_p0),
    .din1(grp_fu_515_p1),
    .ce(1'b1),
    .dout(grp_fu_515_p2)
);

EQ_mul_40s_24s_62_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 62 ))
mul_40s_24s_62_2_1_U66(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_521_p0),
    .din1(grp_fu_521_p1),
    .ce(1'b1),
    .dout(grp_fu_521_p2)
);

EQ_mul_40s_24s_62_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 62 ))
mul_40s_24s_62_2_1_U67(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_527_p0),
    .din1(grp_fu_527_p1),
    .ce(1'b1),
    .dout(grp_fu_527_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln53_fu_325_p2 == 1'd0))) begin
            grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_ap_start_reg <= 1'b1;
        end else if ((grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_ap_ready == 1'b1)) begin
            grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_ap_start_reg <= 1'b1;
        end else if ((grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_ap_ready == 1'b1)) begin
            grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state9) & (((inverse_offset_read_read_fu_102_p2 == 1'd1) & (icmp_ln63_reg_661 == 1'd0)) | ((inverse_offset_read_read_fu_102_p2 == 1'd1) & (icmp_ln63_1_fu_381_p2 == 1'd1))))) begin
            grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_ap_start_reg <= 1'b1;
        end else if ((grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_ap_ready == 1'b1)) begin
            grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_init_twiddle_fu_248_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_init_twiddle_fu_248_ap_start_reg <= 1'b1;
        end else if ((grp_init_twiddle_fu_248_ap_ready == 1'b1)) begin
            grp_init_twiddle_fu_248_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_1_fu_82 <= 11'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        i_1_fu_82 <= add_ln53_reg_651;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        j_reg_226 <= add_ln68_reg_733;
    end else if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln66_fu_429_p2 == 1'd1))) begin
        j_reg_226 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln63_1_fu_381_p2 == 1'd0) & (icmp_ln63_reg_661 == 1'd1))) begin
        k_reg_214 <= 64'd0;
    end else if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln68_fu_452_p2 == 1'd1))) begin
        k_reg_214 <= add_ln66_fu_490_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        phi_mul_reg_237 <= add_ln69_reg_738;
    end else if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln66_fu_429_p2 == 1'd1))) begin
        phi_mul_reg_237 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln63_fu_341_p2 == 1'd1) & (icmp_ln53_fu_325_p2 == 1'd1))) begin
        s_fu_98 <= 32'd1;
    end else if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln66_fu_429_p2 == 1'd0))) begin
        s_fu_98 <= s_3_fu_438_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln53_reg_651 <= add_ln53_fu_330_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        add_ln68_reg_733 <= add_ln68_fu_457_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln68_fu_452_p2 == 1'd0))) begin
        add_ln69_reg_738 <= add_ln69_fu_463_p2;
        add_ln73_reg_753 <= add_ln73_fu_474_p2;
        buf_im_addr_2_reg_763 <= zext_ln73_1_fu_484_p1;
        buf_re_addr_2_reg_758 <= zext_ln73_1_fu_484_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln55_fu_368_p2 == 1'd1))) begin
        buf_im_addr_1_reg_691 <= zext_ln55_fu_362_p1;
        buf_im_addr_reg_681 <= zext_ln53_1_fu_351_p1;
        buf_re_addr_1_reg_686 <= zext_ln55_fu_362_p1;
        buf_re_addr_reg_676 <= zext_ln53_1_fu_351_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        buf_im_addr_3_reg_832 <= zext_ln73_fu_533_p1;
        buf_re_addr_3_reg_827 <= zext_ln73_fu_533_p1;
        r_V_17_reg_807 <= grp_fu_502_p2;
        r_V_19_reg_812 <= grp_fu_515_p2;
        r_V_20_reg_817 <= grp_fu_521_p2;
        r_V_21_reg_822 <= grp_fu_527_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln53_fu_325_p2 == 1'd0))) begin
        empty_54_reg_656 <= empty_54_fu_336_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln63_1_fu_381_p2 == 1'd0) & (icmp_ln63_reg_661 == 1'd1))) begin
        empty_55_reg_717 <= empty_55_fu_425_p1;
        sext_ln66_1_reg_712 <= sext_ln66_1_fu_416_p1;
        sext_ln66_reg_707 <= sext_ln66_fu_412_p1;
        trunc_ln8_reg_702 <= {{m_fu_386_p2[10:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fft_size_cast_reg_629[10 : 0] <= fft_size_cast_fu_310_p1[10 : 0];
        zext_ln53_reg_640[10 : 0] <= zext_ln53_fu_319_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        icmp_ln55_reg_672 <= icmp_ln55_fu_368_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln53_fu_325_p2 == 1'd1))) begin
        icmp_ln63_reg_661 <= icmp_ln63_fu_341_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_logN_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        logN_1_loc_fu_90 <= grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_logN_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        pi_V_reg_843 <= {{ret_V_9_fu_552_p2[61:22]}};
        pr_V_reg_837 <= {{ret_V_fu_538_p2[61:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state12))) begin
        reg_297 <= buf_re_q0;
        reg_301 <= buf_im_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        sub_ln859_1_reg_854 <= sub_ln859_1_fu_583_p2;
        sub_ln859_reg_849 <= sub_ln859_fu_578_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ti_V_reg_778 <= twiddle_im_V_q0;
        tr_V_reg_773 <= twiddle_re_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln66_fu_429_p2 == 1'd1))) begin
        trunc_ln66_reg_725 <= trunc_ln66_fu_434_p1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state18_on_subcall_done)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        buf_im_address0 = buf_im_addr_2_reg_763;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        buf_im_address0 = buf_im_addr_3_reg_832;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        buf_im_address0 = zext_ln73_fu_533_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf_im_address0 = zext_ln73_1_fu_484_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_im_address0 = buf_im_addr_1_reg_691;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_im_address0 = buf_im_addr_reg_681;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_im_address0 = zext_ln55_fu_362_p1;
    end else if (((inverse_offset_read_read_fu_102_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        buf_im_address0 = grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_im_address0;
    end else begin
        buf_im_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state6))) begin
        buf_im_ce0 = 1'b1;
    end else if (((inverse_offset_read_read_fu_102_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        buf_im_ce0 = grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_im_ce0;
    end else begin
        buf_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((inverse_offset_read_read_fu_102_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        buf_im_ce1 = grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_im_ce1;
    end else begin
        buf_im_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        buf_im_d0 = sub_ln859_1_reg_854;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        buf_im_d0 = add_ln859_1_fu_572_p2;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state8))) begin
        buf_im_d0 = buf_im_q0;
    end else if (((inverse_offset_read_read_fu_102_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        buf_im_d0 = grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_im_d0;
    end else begin
        buf_im_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state8) & (icmp_ln55_reg_672 == 1'd1)))) begin
        buf_im_we0 = 1'b1;
    end else if (((inverse_offset_read_read_fu_102_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        buf_im_we0 = grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_im_we0;
    end else begin
        buf_im_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        buf_re_address0 = buf_re_addr_2_reg_758;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        buf_re_address0 = buf_re_addr_3_reg_827;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        buf_re_address0 = zext_ln73_fu_533_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf_re_address0 = zext_ln73_1_fu_484_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_re_address0 = buf_re_addr_1_reg_686;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_re_address0 = buf_re_addr_reg_676;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_re_address0 = zext_ln55_fu_362_p1;
    end else if (((inverse_offset_read_read_fu_102_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        buf_re_address0 = grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_re_address0;
    end else begin
        buf_re_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state6))) begin
        buf_re_ce0 = 1'b1;
    end else if (((inverse_offset_read_read_fu_102_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        buf_re_ce0 = grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_re_ce0;
    end else begin
        buf_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((inverse_offset_read_read_fu_102_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        buf_re_ce1 = grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_re_ce1;
    end else begin
        buf_re_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        buf_re_d0 = sub_ln859_reg_849;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        buf_re_d0 = add_ln859_fu_566_p2;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state8))) begin
        buf_re_d0 = buf_re_q0;
    end else if (((inverse_offset_read_read_fu_102_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        buf_re_d0 = grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_re_d0;
    end else begin
        buf_re_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | ((1'b1 == ap_CS_fsm_state8) & (icmp_ln55_reg_672 == 1'd1)))) begin
        buf_re_we0 = 1'b1;
    end else if (((inverse_offset_read_read_fu_102_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        buf_re_we0 = grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_re_we0;
    end else begin
        buf_re_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        twiddle_im_V_address0 = zext_ln70_fu_468_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        twiddle_im_V_address0 = grp_init_twiddle_fu_248_twiddle_im_V_address0;
    end else begin
        twiddle_im_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        twiddle_im_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        twiddle_im_V_ce0 = grp_init_twiddle_fu_248_twiddle_im_V_ce0;
    end else begin
        twiddle_im_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        twiddle_im_V_we0 = grp_init_twiddle_fu_248_twiddle_im_V_we0;
    end else begin
        twiddle_im_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        twiddle_re_V_address0 = zext_ln70_fu_468_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        twiddle_re_V_address0 = grp_init_twiddle_fu_248_twiddle_re_V_address0;
    end else begin
        twiddle_re_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        twiddle_re_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        twiddle_re_V_ce0 = grp_init_twiddle_fu_248_twiddle_re_V_ce0;
    end else begin
        twiddle_re_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        twiddle_re_V_we0 = grp_init_twiddle_fu_248_twiddle_re_V_we0;
    end else begin
        twiddle_re_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln53_fu_325_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln55_fu_368_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & ((icmp_ln63_1_fu_381_p2 == 1'd1) | (icmp_ln63_reg_661 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln66_fu_429_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln68_fu_452_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state18 : begin
            if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln53_fu_330_p2 = (i_1_fu_82 + 11'd1);

assign add_ln66_fu_490_p2 = ($signed(sext_ln66_reg_707) + $signed(k_reg_214));

assign add_ln68_fu_457_p2 = (j_reg_226 + 32'd1);

assign add_ln69_fu_463_p2 = (phi_mul_reg_237 + empty_55_reg_717);

assign add_ln73_1_fu_479_p2 = (add_ln73_fu_474_p2 + trunc_ln8_reg_702);

assign add_ln73_fu_474_p2 = (trunc_ln68_fu_448_p1 + trunc_ln66_reg_725);

assign add_ln859_1_fu_572_p0 = reg_301;

assign add_ln859_1_fu_572_p2 = (add_ln859_1_fu_572_p0 + pi_V_reg_843);

assign add_ln859_fu_566_p0 = reg_297;

assign add_ln859_fu_566_p2 = (add_ln859_fu_566_p0 + pr_V_reg_837);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state18_on_subcall_done = ((inverse_offset_read_read_fu_102_p2 == 1'd1) & (grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_ap_done == 1'b0) | (grp_init_twiddle_fu_248_ap_done == 1'b0));
end

assign buf_im_address1 = grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_im_address1;

assign buf_re_address1 = grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_buf_re_address1;

assign empty_54_fu_336_p1 = i_1_fu_82[9:0];

assign empty_55_fu_425_p1 = p_lshr_f_fu_420_p2[8:0];

assign fft_size_cast_fu_310_p1 = fft_size;

assign grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_ap_start = grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_ap_start_reg;

assign grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_ap_start = grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_ap_start_reg;

assign grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_ap_start = grp_fft_Pipeline_VITIS_LOOP_90_6_fu_287_ap_start_reg;

assign grp_fu_502_p0 = sext_ln1316_fu_495_p1;

assign grp_fu_502_p1 = sext_ln1319_fu_499_p1;

assign grp_fu_515_p0 = sext_ln1316_1_fu_508_p1;

assign grp_fu_515_p1 = sext_ln1319_1_fu_512_p1;

assign grp_fu_521_p0 = sext_ln1316_fu_495_p1;

assign grp_fu_521_p1 = sext_ln1319_1_fu_512_p1;

assign grp_fu_527_p0 = sext_ln1316_1_fu_508_p1;

assign grp_fu_527_p1 = sext_ln1319_fu_499_p1;

assign grp_init_twiddle_fu_248_ap_start = grp_init_twiddle_fu_248_ap_start_reg;

assign icmp_ln53_fu_325_p2 = ((i_1_fu_82 == fft_size) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_368_p2 = (($signed(zext_ln53_2_fu_356_p1) < $signed(grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_n_out)) ? 1'b1 : 1'b0);

assign icmp_ln63_1_fu_381_p2 = ((s_fu_98 == logN_1_loc_fu_90) ? 1'b1 : 1'b0);

assign icmp_ln63_fu_341_p2 = (($signed(grp_fft_Pipeline_VITIS_LOOP_50_1_fu_272_logN_out) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_429_p2 = (($signed(k_reg_214) < $signed(zext_ln53_reg_640)) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_452_p2 = ((j_reg_226 == sext_ln66_1_reg_712) ? 1'b1 : 1'b0);

assign inverse_offset_read_read_fu_102_p2 = inverse_offset;

assign m2_fu_392_p4 = {{m_fu_386_p2[31:1]}};

assign m_fu_386_p2 = 32'd1 << s_fu_98;

assign p_lshr_f_fu_420_p2 = fft_size_cast_reg_629 >> s_fu_98;

assign ret_V_9_fu_552_p2 = (r_V_21_reg_822 + r_V_20_reg_817);

assign ret_V_fu_538_p2 = (r_V_17_reg_807 - r_V_19_reg_812);

assign s_3_fu_438_p2 = (s_fu_98 + 32'd1);

assign sext_ln1316_1_fu_508_p1 = reg_301;

assign sext_ln1316_fu_495_p1 = reg_297;

assign sext_ln1319_1_fu_512_p1 = $signed(ti_V_reg_778);

assign sext_ln1319_fu_499_p1 = $signed(tr_V_reg_773);

assign sext_ln66_1_fu_416_p1 = $signed(m2_fu_392_p4);

assign sext_ln66_fu_412_p1 = m_fu_386_p2;

assign sub_ln859_1_fu_583_p0 = reg_301;

assign sub_ln859_1_fu_583_p2 = (sub_ln859_1_fu_583_p0 - pi_V_reg_843);

assign sub_ln859_fu_578_p0 = reg_297;

assign sub_ln859_fu_578_p2 = (sub_ln859_fu_578_p0 - pr_V_reg_837);

assign trunc_ln66_fu_434_p1 = k_reg_214[9:0];

assign trunc_ln68_fu_448_p1 = j_reg_226[9:0];

assign zext_ln53_1_fu_351_p1 = i_1_fu_82;

assign zext_ln53_2_fu_356_p1 = i_1_fu_82;

assign zext_ln53_fu_319_p1 = fft_size;

assign zext_ln55_fu_362_p1 = grp_fft_Pipeline_VITIS_LOOP_38_1_fu_280_n_out;

assign zext_ln70_fu_468_p1 = phi_mul_reg_237;

assign zext_ln73_1_fu_484_p1 = add_ln73_1_fu_479_p2;

assign zext_ln73_fu_533_p1 = add_ln73_reg_753;

always @ (posedge ap_clk) begin
    fft_size_cast_reg_629[31:11] <= 21'b000000000000000000000;
    zext_ln53_reg_640[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
end

endmodule //EQ_fft
