// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module EQ_fft_Pipeline_VITIS_LOOP_90_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fft_size,
        buf_re_address0,
        buf_re_ce0,
        buf_re_we0,
        buf_re_d0,
        buf_re_address1,
        buf_re_ce1,
        buf_re_q1,
        conv_i_i_i28,
        buf_im_address0,
        buf_im_ce0,
        buf_im_we0,
        buf_im_d0,
        buf_im_address1,
        buf_im_ce1,
        buf_im_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [10:0] fft_size;
output  [9:0] buf_re_address0;
output   buf_re_ce0;
output   buf_re_we0;
output  [39:0] buf_re_d0;
output  [9:0] buf_re_address1;
output   buf_re_ce1;
input  [39:0] buf_re_q1;
input  [10:0] conv_i_i_i28;
output  [9:0] buf_im_address0;
output   buf_im_ce0;
output   buf_im_we0;
output  [39:0] buf_im_d0;
output  [9:0] buf_im_address1;
output   buf_im_ce1;
input  [39:0] buf_im_q1;

reg ap_idle;
reg buf_re_ce0;
reg buf_re_we0;
reg buf_re_ce1;
reg buf_im_ce0;
reg buf_im_we0;
reg buf_im_ce1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter37;
reg    ap_enable_reg_pp0_iter38;
reg    ap_enable_reg_pp0_iter39;
reg    ap_enable_reg_pp0_iter40;
reg    ap_enable_reg_pp0_iter41;
reg    ap_enable_reg_pp0_iter42;
reg    ap_enable_reg_pp0_iter43;
reg    ap_enable_reg_pp0_iter44;
reg    ap_enable_reg_pp0_iter45;
reg    ap_enable_reg_pp0_iter46;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
wire    ap_block_state25_pp0_stage0_iter24;
wire    ap_block_state26_pp0_stage0_iter25;
wire    ap_block_state27_pp0_stage0_iter26;
wire    ap_block_state28_pp0_stage0_iter27;
wire    ap_block_state29_pp0_stage0_iter28;
wire    ap_block_state30_pp0_stage0_iter29;
wire    ap_block_state31_pp0_stage0_iter30;
wire    ap_block_state32_pp0_stage0_iter31;
wire    ap_block_state33_pp0_stage0_iter32;
wire    ap_block_state34_pp0_stage0_iter33;
wire    ap_block_state35_pp0_stage0_iter34;
wire    ap_block_state36_pp0_stage0_iter35;
wire    ap_block_state37_pp0_stage0_iter36;
wire    ap_block_state38_pp0_stage0_iter37;
wire    ap_block_state39_pp0_stage0_iter38;
wire    ap_block_state40_pp0_stage0_iter39;
wire    ap_block_state41_pp0_stage0_iter40;
wire    ap_block_state42_pp0_stage0_iter41;
wire    ap_block_state43_pp0_stage0_iter42;
wire    ap_block_state44_pp0_stage0_iter43;
wire    ap_block_state45_pp0_stage0_iter44;
wire    ap_block_state46_pp0_stage0_iter45;
wire    ap_block_state47_pp0_stage0_iter46;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln90_fu_96_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [39:0] conv_i_i_i28_cast_fu_84_p1;
reg   [39:0] conv_i_i_i28_cast_reg_134;
wire    ap_block_pp0_stage0_11001;
reg   [9:0] buf_re_addr_reg_144;
reg   [9:0] buf_re_addr_reg_144_pp0_iter1_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter2_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter3_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter4_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter5_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter6_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter7_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter8_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter9_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter10_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter11_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter12_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter13_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter14_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter15_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter16_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter17_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter18_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter19_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter20_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter21_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter22_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter23_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter24_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter25_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter26_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter27_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter28_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter29_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter30_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter31_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter32_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter33_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter34_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter35_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter36_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter37_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter38_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter39_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter40_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter41_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter42_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter43_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter44_reg;
reg   [9:0] buf_re_addr_reg_144_pp0_iter45_reg;
reg   [9:0] buf_im_addr_reg_150;
reg   [9:0] buf_im_addr_reg_150_pp0_iter1_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter2_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter3_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter4_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter5_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter6_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter7_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter8_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter9_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter10_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter11_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter12_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter13_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter14_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter15_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter16_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter17_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter18_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter19_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter20_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter21_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter22_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter23_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter24_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter25_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter26_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter27_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter28_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter29_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter30_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter31_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter32_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter33_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter34_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter35_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter36_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter37_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter38_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter39_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter40_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter41_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter42_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter43_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter44_reg;
reg   [9:0] buf_im_addr_reg_150_pp0_iter45_reg;
reg   [39:0] t_V_reg_156;
reg   [39:0] t_V_1_reg_161;
wire   [39:0] grp_fu_119_p2;
reg   [39:0] sdiv_ln1349_reg_166;
wire   [39:0] grp_fu_123_p2;
reg   [39:0] sdiv_ln1349_1_reg_171;
wire   [63:0] i_3_cast_fu_108_p1;
wire    ap_block_pp0_stage0;
reg   [10:0] i_fu_34;
wire   [10:0] add_ln90_fu_102_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_i_2;
wire   [11:0] grp_fu_119_p1;
wire   [11:0] grp_fu_123_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg    ap_loop_exit_ready_pp0_iter35_reg;
reg    ap_loop_exit_ready_pp0_iter36_reg;
reg    ap_loop_exit_ready_pp0_iter37_reg;
reg    ap_loop_exit_ready_pp0_iter38_reg;
reg    ap_loop_exit_ready_pp0_iter39_reg;
reg    ap_loop_exit_ready_pp0_iter40_reg;
reg    ap_loop_exit_ready_pp0_iter41_reg;
reg    ap_loop_exit_ready_pp0_iter42_reg;
reg    ap_loop_exit_ready_pp0_iter43_reg;
reg    ap_loop_exit_ready_pp0_iter44_reg;
reg    ap_loop_exit_ready_pp0_iter45_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
#0 ap_enable_reg_pp0_iter38 = 1'b0;
#0 ap_enable_reg_pp0_iter39 = 1'b0;
#0 ap_enable_reg_pp0_iter40 = 1'b0;
#0 ap_enable_reg_pp0_iter41 = 1'b0;
#0 ap_enable_reg_pp0_iter42 = 1'b0;
#0 ap_enable_reg_pp0_iter43 = 1'b0;
#0 ap_enable_reg_pp0_iter44 = 1'b0;
#0 ap_enable_reg_pp0_iter45 = 1'b0;
#0 ap_enable_reg_pp0_iter46 = 1'b0;
#0 ap_done_reg = 1'b0;
end

EQ_sdiv_40ns_12ns_40_44_1 #(
    .ID( 1 ),
    .NUM_STAGE( 44 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 40 ))
sdiv_40ns_12ns_40_44_1_U57(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(t_V_reg_156),
    .din1(grp_fu_119_p1),
    .ce(1'b1),
    .dout(grp_fu_119_p2)
);

EQ_sdiv_40ns_12ns_40_44_1 #(
    .ID( 1 ),
    .NUM_STAGE( 44 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 40 ))
sdiv_40ns_12ns_40_44_1_U58(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(t_V_1_reg_161),
    .din1(grp_fu_123_p1),
    .ce(1'b1),
    .dout(grp_fu_123_p2)
);

EQ_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter45_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter38 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter39 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter40 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter40 <= ap_enable_reg_pp0_iter39;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter41 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter41 <= ap_enable_reg_pp0_iter40;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter42 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter42 <= ap_enable_reg_pp0_iter41;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter43 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter43 <= ap_enable_reg_pp0_iter42;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter44 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter44 <= ap_enable_reg_pp0_iter43;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter45 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter45 <= ap_enable_reg_pp0_iter44;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter46 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter46 <= ap_enable_reg_pp0_iter45;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln90_fu_96_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_34 <= add_ln90_fu_102_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_34 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
        ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
        ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
        ap_loop_exit_ready_pp0_iter37_reg <= ap_loop_exit_ready_pp0_iter36_reg;
        ap_loop_exit_ready_pp0_iter38_reg <= ap_loop_exit_ready_pp0_iter37_reg;
        ap_loop_exit_ready_pp0_iter39_reg <= ap_loop_exit_ready_pp0_iter38_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter40_reg <= ap_loop_exit_ready_pp0_iter39_reg;
        ap_loop_exit_ready_pp0_iter41_reg <= ap_loop_exit_ready_pp0_iter40_reg;
        ap_loop_exit_ready_pp0_iter42_reg <= ap_loop_exit_ready_pp0_iter41_reg;
        ap_loop_exit_ready_pp0_iter43_reg <= ap_loop_exit_ready_pp0_iter42_reg;
        ap_loop_exit_ready_pp0_iter44_reg <= ap_loop_exit_ready_pp0_iter43_reg;
        ap_loop_exit_ready_pp0_iter45_reg <= ap_loop_exit_ready_pp0_iter44_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        buf_im_addr_reg_150_pp0_iter10_reg <= buf_im_addr_reg_150_pp0_iter9_reg;
        buf_im_addr_reg_150_pp0_iter11_reg <= buf_im_addr_reg_150_pp0_iter10_reg;
        buf_im_addr_reg_150_pp0_iter12_reg <= buf_im_addr_reg_150_pp0_iter11_reg;
        buf_im_addr_reg_150_pp0_iter13_reg <= buf_im_addr_reg_150_pp0_iter12_reg;
        buf_im_addr_reg_150_pp0_iter14_reg <= buf_im_addr_reg_150_pp0_iter13_reg;
        buf_im_addr_reg_150_pp0_iter15_reg <= buf_im_addr_reg_150_pp0_iter14_reg;
        buf_im_addr_reg_150_pp0_iter16_reg <= buf_im_addr_reg_150_pp0_iter15_reg;
        buf_im_addr_reg_150_pp0_iter17_reg <= buf_im_addr_reg_150_pp0_iter16_reg;
        buf_im_addr_reg_150_pp0_iter18_reg <= buf_im_addr_reg_150_pp0_iter17_reg;
        buf_im_addr_reg_150_pp0_iter19_reg <= buf_im_addr_reg_150_pp0_iter18_reg;
        buf_im_addr_reg_150_pp0_iter20_reg <= buf_im_addr_reg_150_pp0_iter19_reg;
        buf_im_addr_reg_150_pp0_iter21_reg <= buf_im_addr_reg_150_pp0_iter20_reg;
        buf_im_addr_reg_150_pp0_iter22_reg <= buf_im_addr_reg_150_pp0_iter21_reg;
        buf_im_addr_reg_150_pp0_iter23_reg <= buf_im_addr_reg_150_pp0_iter22_reg;
        buf_im_addr_reg_150_pp0_iter24_reg <= buf_im_addr_reg_150_pp0_iter23_reg;
        buf_im_addr_reg_150_pp0_iter25_reg <= buf_im_addr_reg_150_pp0_iter24_reg;
        buf_im_addr_reg_150_pp0_iter26_reg <= buf_im_addr_reg_150_pp0_iter25_reg;
        buf_im_addr_reg_150_pp0_iter27_reg <= buf_im_addr_reg_150_pp0_iter26_reg;
        buf_im_addr_reg_150_pp0_iter28_reg <= buf_im_addr_reg_150_pp0_iter27_reg;
        buf_im_addr_reg_150_pp0_iter29_reg <= buf_im_addr_reg_150_pp0_iter28_reg;
        buf_im_addr_reg_150_pp0_iter2_reg <= buf_im_addr_reg_150_pp0_iter1_reg;
        buf_im_addr_reg_150_pp0_iter30_reg <= buf_im_addr_reg_150_pp0_iter29_reg;
        buf_im_addr_reg_150_pp0_iter31_reg <= buf_im_addr_reg_150_pp0_iter30_reg;
        buf_im_addr_reg_150_pp0_iter32_reg <= buf_im_addr_reg_150_pp0_iter31_reg;
        buf_im_addr_reg_150_pp0_iter33_reg <= buf_im_addr_reg_150_pp0_iter32_reg;
        buf_im_addr_reg_150_pp0_iter34_reg <= buf_im_addr_reg_150_pp0_iter33_reg;
        buf_im_addr_reg_150_pp0_iter35_reg <= buf_im_addr_reg_150_pp0_iter34_reg;
        buf_im_addr_reg_150_pp0_iter36_reg <= buf_im_addr_reg_150_pp0_iter35_reg;
        buf_im_addr_reg_150_pp0_iter37_reg <= buf_im_addr_reg_150_pp0_iter36_reg;
        buf_im_addr_reg_150_pp0_iter38_reg <= buf_im_addr_reg_150_pp0_iter37_reg;
        buf_im_addr_reg_150_pp0_iter39_reg <= buf_im_addr_reg_150_pp0_iter38_reg;
        buf_im_addr_reg_150_pp0_iter3_reg <= buf_im_addr_reg_150_pp0_iter2_reg;
        buf_im_addr_reg_150_pp0_iter40_reg <= buf_im_addr_reg_150_pp0_iter39_reg;
        buf_im_addr_reg_150_pp0_iter41_reg <= buf_im_addr_reg_150_pp0_iter40_reg;
        buf_im_addr_reg_150_pp0_iter42_reg <= buf_im_addr_reg_150_pp0_iter41_reg;
        buf_im_addr_reg_150_pp0_iter43_reg <= buf_im_addr_reg_150_pp0_iter42_reg;
        buf_im_addr_reg_150_pp0_iter44_reg <= buf_im_addr_reg_150_pp0_iter43_reg;
        buf_im_addr_reg_150_pp0_iter45_reg <= buf_im_addr_reg_150_pp0_iter44_reg;
        buf_im_addr_reg_150_pp0_iter4_reg <= buf_im_addr_reg_150_pp0_iter3_reg;
        buf_im_addr_reg_150_pp0_iter5_reg <= buf_im_addr_reg_150_pp0_iter4_reg;
        buf_im_addr_reg_150_pp0_iter6_reg <= buf_im_addr_reg_150_pp0_iter5_reg;
        buf_im_addr_reg_150_pp0_iter7_reg <= buf_im_addr_reg_150_pp0_iter6_reg;
        buf_im_addr_reg_150_pp0_iter8_reg <= buf_im_addr_reg_150_pp0_iter7_reg;
        buf_im_addr_reg_150_pp0_iter9_reg <= buf_im_addr_reg_150_pp0_iter8_reg;
        buf_re_addr_reg_144_pp0_iter10_reg <= buf_re_addr_reg_144_pp0_iter9_reg;
        buf_re_addr_reg_144_pp0_iter11_reg <= buf_re_addr_reg_144_pp0_iter10_reg;
        buf_re_addr_reg_144_pp0_iter12_reg <= buf_re_addr_reg_144_pp0_iter11_reg;
        buf_re_addr_reg_144_pp0_iter13_reg <= buf_re_addr_reg_144_pp0_iter12_reg;
        buf_re_addr_reg_144_pp0_iter14_reg <= buf_re_addr_reg_144_pp0_iter13_reg;
        buf_re_addr_reg_144_pp0_iter15_reg <= buf_re_addr_reg_144_pp0_iter14_reg;
        buf_re_addr_reg_144_pp0_iter16_reg <= buf_re_addr_reg_144_pp0_iter15_reg;
        buf_re_addr_reg_144_pp0_iter17_reg <= buf_re_addr_reg_144_pp0_iter16_reg;
        buf_re_addr_reg_144_pp0_iter18_reg <= buf_re_addr_reg_144_pp0_iter17_reg;
        buf_re_addr_reg_144_pp0_iter19_reg <= buf_re_addr_reg_144_pp0_iter18_reg;
        buf_re_addr_reg_144_pp0_iter20_reg <= buf_re_addr_reg_144_pp0_iter19_reg;
        buf_re_addr_reg_144_pp0_iter21_reg <= buf_re_addr_reg_144_pp0_iter20_reg;
        buf_re_addr_reg_144_pp0_iter22_reg <= buf_re_addr_reg_144_pp0_iter21_reg;
        buf_re_addr_reg_144_pp0_iter23_reg <= buf_re_addr_reg_144_pp0_iter22_reg;
        buf_re_addr_reg_144_pp0_iter24_reg <= buf_re_addr_reg_144_pp0_iter23_reg;
        buf_re_addr_reg_144_pp0_iter25_reg <= buf_re_addr_reg_144_pp0_iter24_reg;
        buf_re_addr_reg_144_pp0_iter26_reg <= buf_re_addr_reg_144_pp0_iter25_reg;
        buf_re_addr_reg_144_pp0_iter27_reg <= buf_re_addr_reg_144_pp0_iter26_reg;
        buf_re_addr_reg_144_pp0_iter28_reg <= buf_re_addr_reg_144_pp0_iter27_reg;
        buf_re_addr_reg_144_pp0_iter29_reg <= buf_re_addr_reg_144_pp0_iter28_reg;
        buf_re_addr_reg_144_pp0_iter2_reg <= buf_re_addr_reg_144_pp0_iter1_reg;
        buf_re_addr_reg_144_pp0_iter30_reg <= buf_re_addr_reg_144_pp0_iter29_reg;
        buf_re_addr_reg_144_pp0_iter31_reg <= buf_re_addr_reg_144_pp0_iter30_reg;
        buf_re_addr_reg_144_pp0_iter32_reg <= buf_re_addr_reg_144_pp0_iter31_reg;
        buf_re_addr_reg_144_pp0_iter33_reg <= buf_re_addr_reg_144_pp0_iter32_reg;
        buf_re_addr_reg_144_pp0_iter34_reg <= buf_re_addr_reg_144_pp0_iter33_reg;
        buf_re_addr_reg_144_pp0_iter35_reg <= buf_re_addr_reg_144_pp0_iter34_reg;
        buf_re_addr_reg_144_pp0_iter36_reg <= buf_re_addr_reg_144_pp0_iter35_reg;
        buf_re_addr_reg_144_pp0_iter37_reg <= buf_re_addr_reg_144_pp0_iter36_reg;
        buf_re_addr_reg_144_pp0_iter38_reg <= buf_re_addr_reg_144_pp0_iter37_reg;
        buf_re_addr_reg_144_pp0_iter39_reg <= buf_re_addr_reg_144_pp0_iter38_reg;
        buf_re_addr_reg_144_pp0_iter3_reg <= buf_re_addr_reg_144_pp0_iter2_reg;
        buf_re_addr_reg_144_pp0_iter40_reg <= buf_re_addr_reg_144_pp0_iter39_reg;
        buf_re_addr_reg_144_pp0_iter41_reg <= buf_re_addr_reg_144_pp0_iter40_reg;
        buf_re_addr_reg_144_pp0_iter42_reg <= buf_re_addr_reg_144_pp0_iter41_reg;
        buf_re_addr_reg_144_pp0_iter43_reg <= buf_re_addr_reg_144_pp0_iter42_reg;
        buf_re_addr_reg_144_pp0_iter44_reg <= buf_re_addr_reg_144_pp0_iter43_reg;
        buf_re_addr_reg_144_pp0_iter45_reg <= buf_re_addr_reg_144_pp0_iter44_reg;
        buf_re_addr_reg_144_pp0_iter4_reg <= buf_re_addr_reg_144_pp0_iter3_reg;
        buf_re_addr_reg_144_pp0_iter5_reg <= buf_re_addr_reg_144_pp0_iter4_reg;
        buf_re_addr_reg_144_pp0_iter6_reg <= buf_re_addr_reg_144_pp0_iter5_reg;
        buf_re_addr_reg_144_pp0_iter7_reg <= buf_re_addr_reg_144_pp0_iter6_reg;
        buf_re_addr_reg_144_pp0_iter8_reg <= buf_re_addr_reg_144_pp0_iter7_reg;
        buf_re_addr_reg_144_pp0_iter9_reg <= buf_re_addr_reg_144_pp0_iter8_reg;
        sdiv_ln1349_1_reg_171 <= grp_fu_123_p2;
        sdiv_ln1349_reg_166 <= grp_fu_119_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        buf_im_addr_reg_150_pp0_iter1_reg <= buf_im_addr_reg_150;
        buf_re_addr_reg_144_pp0_iter1_reg <= buf_re_addr_reg_144;
        conv_i_i_i28_cast_reg_134[10 : 0] <= conv_i_i_i28_cast_fu_84_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln90_fu_96_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_im_addr_reg_150 <= i_3_cast_fu_108_p1;
        buf_re_addr_reg_144 <= i_3_cast_fu_108_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        t_V_1_reg_161 <= buf_im_q1;
        t_V_reg_156 <= buf_re_q1;
    end
end

always @ (*) begin
    if (((icmp_ln90_fu_96_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter45_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter46 == 1'b0) & (ap_enable_reg_pp0_iter45 == 1'b0) & (ap_enable_reg_pp0_iter44 == 1'b0) & (ap_enable_reg_pp0_iter43 == 1'b0) & (ap_enable_reg_pp0_iter42 == 1'b0) & (ap_enable_reg_pp0_iter41 == 1'b0) & (ap_enable_reg_pp0_iter40 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 11'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_34;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter46 == 1'b1))) begin
        buf_im_ce0 = 1'b1;
    end else begin
        buf_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_im_ce1 = 1'b1;
    end else begin
        buf_im_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter46 == 1'b1))) begin
        buf_im_we0 = 1'b1;
    end else begin
        buf_im_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter46 == 1'b1))) begin
        buf_re_ce0 = 1'b1;
    end else begin
        buf_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_re_ce1 = 1'b1;
    end else begin
        buf_re_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter46 == 1'b1))) begin
        buf_re_we0 = 1'b1;
    end else begin
        buf_re_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln90_fu_102_p2 = (ap_sig_allocacmp_i_2 + 11'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter29 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter30 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter31 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter32 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter33 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage0_iter34 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage0_iter35 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage0_iter36 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage0_iter37 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage0_iter38 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp0_stage0_iter39 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp0_stage0_iter40 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp0_stage0_iter41 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp0_stage0_iter42 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp0_stage0_iter43 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp0_stage0_iter44 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp0_stage0_iter45 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp0_stage0_iter46 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign buf_im_address0 = buf_im_addr_reg_150_pp0_iter45_reg;

assign buf_im_address1 = i_3_cast_fu_108_p1;

assign buf_im_d0 = sdiv_ln1349_1_reg_171;

assign buf_re_address0 = buf_re_addr_reg_144_pp0_iter45_reg;

assign buf_re_address1 = i_3_cast_fu_108_p1;

assign buf_re_d0 = sdiv_ln1349_reg_166;

assign conv_i_i_i28_cast_fu_84_p1 = conv_i_i_i28;

assign grp_fu_119_p1 = conv_i_i_i28_cast_reg_134;

assign grp_fu_123_p1 = conv_i_i_i28_cast_reg_134;

assign i_3_cast_fu_108_p1 = ap_sig_allocacmp_i_2;

assign icmp_ln90_fu_96_p2 = ((ap_sig_allocacmp_i_2 == fft_size) ? 1'b1 : 1'b0);

always @ (posedge ap_clk) begin
    conv_i_i_i28_cast_reg_134[39:11] <= 29'b00000000000000000000000000000;
end

endmodule //EQ_fft_Pipeline_VITIS_LOOP_90_6
