// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="EQ_EQ,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.075000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=24,HLS_SYN_DSP=0,HLS_SYN_FF=25542,HLS_SYN_LUT=24058,HLS_VERSION=2022_1}" *)

module EQ (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [1:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [4:0] in_stream_TID;
input  [5:0] in_stream_TDEST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [1:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [4:0] out_stream_TID;
output  [5:0] out_stream_TDEST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] sample_rate;
reg   [9:0] p_lshr_f6_cast_reg_268;
wire    ap_CS_fsm_state4;
wire   [9:0] trunc_ln98_fu_244_p1;
reg   [9:0] trunc_ln98_reg_274;
wire   [10:0] sub_fu_253_p2;
reg   [10:0] sub_reg_279;
wire    ap_CS_fsm_state12;
reg   [9:0] buf_re_V_address0;
reg    buf_re_V_ce0;
reg    buf_re_V_we0;
reg   [39:0] buf_re_V_d0;
wire   [39:0] buf_re_V_q0;
reg    buf_re_V_ce1;
wire   [39:0] buf_re_V_q1;
reg   [9:0] buf_im_V_address0;
reg    buf_im_V_ce0;
reg    buf_im_V_we0;
reg   [39:0] buf_im_V_d0;
wire   [39:0] buf_im_V_q0;
reg    buf_im_V_ce1;
wire   [39:0] buf_im_V_q1;
wire    grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_ap_start;
wire    grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_ap_done;
wire    grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_ap_idle;
wire    grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_ap_ready;
wire    grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_in_stream_TREADY;
wire   [9:0] grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_re_V_address0;
wire    grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_re_V_ce0;
wire    grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_re_V_we0;
wire   [39:0] grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_re_V_d0;
wire   [9:0] grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_im_V_address0;
wire    grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_im_V_ce0;
wire    grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_im_V_we0;
wire   [39:0] grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_im_V_d0;
wire   [10:0] grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_count_out;
wire    grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_count_out_ap_vld;
wire    grp_fft_fu_175_ap_start;
wire    grp_fft_fu_175_ap_done;
wire    grp_fft_fu_175_ap_idle;
wire    grp_fft_fu_175_ap_ready;
wire   [9:0] grp_fft_fu_175_buf_re_address0;
wire    grp_fft_fu_175_buf_re_ce0;
wire    grp_fft_fu_175_buf_re_we0;
wire   [39:0] grp_fft_fu_175_buf_re_d0;
wire   [9:0] grp_fft_fu_175_buf_re_address1;
wire    grp_fft_fu_175_buf_re_ce1;
wire   [9:0] grp_fft_fu_175_buf_im_address0;
wire    grp_fft_fu_175_buf_im_ce0;
wire    grp_fft_fu_175_buf_im_we0;
wire   [39:0] grp_fft_fu_175_buf_im_d0;
wire   [9:0] grp_fft_fu_175_buf_im_address1;
wire    grp_fft_fu_175_buf_im_ce1;
reg    grp_fft_fu_175_inverse_offset;
wire    grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_ap_start;
wire    grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_ap_done;
wire    grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_ap_idle;
wire    grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_ap_ready;
wire   [9:0] grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_re_V_address0;
wire    grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_re_V_ce0;
wire    grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_re_V_we0;
wire   [39:0] grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_re_V_d0;
wire   [9:0] grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_im_V_address0;
wire    grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_im_V_ce0;
wire    grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_im_V_we0;
wire   [39:0] grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_im_V_d0;
wire    grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_ap_start;
wire    grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_ap_done;
wire    grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_ap_idle;
wire    grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_ap_ready;
wire    grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TREADY;
wire   [9:0] grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_buf_re_V_address0;
wire    grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_buf_re_V_ce0;
wire   [31:0] grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TDATA;
wire    grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TVALID;
wire   [3:0] grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TKEEP;
wire   [3:0] grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TSTRB;
wire   [1:0] grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TUSER;
wire   [0:0] grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TLAST;
wire   [4:0] grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TID;
wire   [5:0] grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TDEST;
reg    grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_fft_fu_175_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state11;
reg    grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state8;
wire   [63:0] zext_ln98_fu_248_p1;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state14;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_user_V_U_apdone_blk;
wire   [1:0] in_stream_TUSER_int_regslice;
wire    regslice_both_in_stream_V_user_V_U_vld_out;
wire    regslice_both_in_stream_V_user_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire    regslice_both_in_stream_V_id_V_U_apdone_blk;
wire   [4:0] in_stream_TID_int_regslice;
wire    regslice_both_in_stream_V_id_V_U_vld_out;
wire    regslice_both_in_stream_V_id_V_U_ack_in;
wire    regslice_both_in_stream_V_dest_V_U_apdone_blk;
wire   [5:0] in_stream_TDEST_int_regslice;
wire    regslice_both_in_stream_V_dest_V_U_vld_out;
wire    regslice_both_in_stream_V_dest_V_U_ack_in;
wire    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_user_V_U_apdone_blk;
wire    regslice_both_out_stream_V_user_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_user_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    regslice_both_out_stream_V_id_V_U_apdone_blk;
wire    regslice_both_out_stream_V_id_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_id_V_U_vld_out;
wire    regslice_both_out_stream_V_dest_V_U_apdone_blk;
wire    regslice_both_out_stream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_ap_start_reg = 1'b0;
#0 grp_fft_fu_175_ap_start_reg = 1'b0;
#0 grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_ap_start_reg = 1'b0;
#0 grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_ap_start_reg = 1'b0;
end

EQ_buf_re_V_RAM_AUTO_1R1W #(
    .DataWidth( 40 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
buf_re_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buf_re_V_address0),
    .ce0(buf_re_V_ce0),
    .we0(buf_re_V_we0),
    .d0(buf_re_V_d0),
    .q0(buf_re_V_q0),
    .address1(grp_fft_fu_175_buf_re_address1),
    .ce1(buf_re_V_ce1),
    .q1(buf_re_V_q1)
);

EQ_buf_re_V_RAM_AUTO_1R1W #(
    .DataWidth( 40 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
buf_im_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buf_im_V_address0),
    .ce0(buf_im_V_ce0),
    .we0(buf_im_V_we0),
    .d0(buf_im_V_d0),
    .q0(buf_im_V_q0),
    .address1(grp_fft_fu_175_buf_im_address1),
    .ce1(buf_im_V_ce1),
    .q1(buf_im_V_q1)
);

EQ_EQ_Pipeline_VITIS_LOOP_165_1 grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_ap_start),
    .ap_done(grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_ap_done),
    .ap_idle(grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_ap_idle),
    .ap_ready(grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP_int_regslice),
    .in_stream_TSTRB(in_stream_TSTRB_int_regslice),
    .in_stream_TUSER(in_stream_TUSER_int_regslice),
    .in_stream_TLAST(in_stream_TLAST_int_regslice),
    .in_stream_TID(in_stream_TID_int_regslice),
    .in_stream_TDEST(in_stream_TDEST_int_regslice),
    .buf_re_V_address0(grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_re_V_address0),
    .buf_re_V_ce0(grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_re_V_ce0),
    .buf_re_V_we0(grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_re_V_we0),
    .buf_re_V_d0(grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_re_V_d0),
    .buf_im_V_address0(grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_im_V_address0),
    .buf_im_V_ce0(grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_im_V_ce0),
    .buf_im_V_we0(grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_im_V_we0),
    .buf_im_V_d0(grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_im_V_d0),
    .count_out(grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_count_out),
    .count_out_ap_vld(grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_count_out_ap_vld)
);

EQ_fft grp_fft_fu_175(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_fft_fu_175_ap_start),
    .ap_done(grp_fft_fu_175_ap_done),
    .ap_idle(grp_fft_fu_175_ap_idle),
    .ap_ready(grp_fft_fu_175_ap_ready),
    .buf_re_address0(grp_fft_fu_175_buf_re_address0),
    .buf_re_ce0(grp_fft_fu_175_buf_re_ce0),
    .buf_re_we0(grp_fft_fu_175_buf_re_we0),
    .buf_re_d0(grp_fft_fu_175_buf_re_d0),
    .buf_re_q0(buf_re_V_q0),
    .buf_re_address1(grp_fft_fu_175_buf_re_address1),
    .buf_re_ce1(grp_fft_fu_175_buf_re_ce1),
    .buf_re_q1(buf_re_V_q1),
    .buf_im_address0(grp_fft_fu_175_buf_im_address0),
    .buf_im_ce0(grp_fft_fu_175_buf_im_ce0),
    .buf_im_we0(grp_fft_fu_175_buf_im_we0),
    .buf_im_d0(grp_fft_fu_175_buf_im_d0),
    .buf_im_q0(buf_im_V_q0),
    .buf_im_address1(grp_fft_fu_175_buf_im_address1),
    .buf_im_ce1(grp_fft_fu_175_buf_im_ce1),
    .buf_im_q1(buf_im_V_q1),
    .fft_size(grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_count_out),
    .inverse_offset(grp_fft_fu_175_inverse_offset)
);

EQ_EQ_Pipeline_VITIS_LOOP_98_1 grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_ap_start),
    .ap_done(grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_ap_done),
    .ap_idle(grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_ap_idle),
    .ap_ready(grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_ap_ready),
    .p_lshr_f6_cast(p_lshr_f6_cast_reg_268),
    .buf_re_V_address0(grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_re_V_address0),
    .buf_re_V_ce0(grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_re_V_ce0),
    .buf_re_V_we0(grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_re_V_we0),
    .buf_re_V_d0(grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_re_V_d0),
    .buf_re_V_q0(buf_re_V_q0),
    .buf_im_V_address0(grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_im_V_address0),
    .buf_im_V_ce0(grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_im_V_ce0),
    .buf_im_V_we0(grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_im_V_we0),
    .buf_im_V_d0(grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_im_V_d0),
    .buf_im_V_q0(buf_im_V_q0),
    .trunc_ln10(trunc_ln98_reg_274)
);

EQ_EQ_Pipeline_VITIS_LOOP_187_2 grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_ap_start),
    .ap_done(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_ap_done),
    .ap_idle(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_ap_idle),
    .ap_ready(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_ap_ready),
    .out_stream_TREADY(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TREADY),
    .count_reload(grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_count_out),
    .buf_re_V_address0(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_buf_re_V_address0),
    .buf_re_V_ce0(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_buf_re_V_ce0),
    .buf_re_V_q0(buf_re_V_q0),
    .sext_ln187(sub_reg_279),
    .out_stream_TDATA(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TDATA),
    .out_stream_TVALID(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TVALID),
    .out_stream_TKEEP(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TKEEP),
    .out_stream_TSTRB(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TSTRB),
    .out_stream_TUSER(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TUSER),
    .out_stream_TLAST(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TLAST),
    .out_stream_TID(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TID),
    .out_stream_TDEST(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TDEST)
);

EQ_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .sample_rate(sample_rate),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

EQ_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

EQ_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

EQ_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

EQ_regslice_both #(
    .DataWidth( 2 ))
regslice_both_in_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TUSER),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_user_V_U_ack_in),
    .data_out(in_stream_TUSER_int_regslice),
    .vld_out(regslice_both_in_stream_V_user_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_user_V_U_apdone_blk)
);

EQ_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

EQ_regslice_both #(
    .DataWidth( 5 ))
regslice_both_in_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TID),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_id_V_U_ack_in),
    .data_out(in_stream_TID_int_regslice),
    .vld_out(regslice_both_in_stream_V_id_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_id_V_U_apdone_blk)
);

EQ_regslice_both #(
    .DataWidth( 6 ))
regslice_both_in_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDEST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_dest_V_U_ack_in),
    .data_out(in_stream_TDEST_int_regslice),
    .vld_out(regslice_both_in_stream_V_dest_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_dest_V_U_apdone_blk)
);

EQ_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TDATA),
    .vld_in(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TVALID),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

EQ_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TKEEP),
    .vld_in(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

EQ_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TSTRB),
    .vld_in(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

EQ_regslice_both #(
    .DataWidth( 2 ))
regslice_both_out_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TUSER),
    .vld_in(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_user_V_U_ack_in_dummy),
    .data_out(out_stream_TUSER),
    .vld_out(regslice_both_out_stream_V_user_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_user_V_U_apdone_blk)
);

EQ_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TLAST),
    .vld_in(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

EQ_regslice_both #(
    .DataWidth( 5 ))
regslice_both_out_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TID),
    .vld_in(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_id_V_U_ack_in_dummy),
    .data_out(out_stream_TID),
    .vld_out(regslice_both_out_stream_V_id_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_id_V_U_apdone_blk)
);

EQ_regslice_both #(
    .DataWidth( 6 ))
regslice_both_out_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TDEST),
    .vld_in(grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_dest_V_U_ack_in_dummy),
    .data_out(out_stream_TDEST),
    .vld_out(regslice_both_out_stream_V_dest_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_ap_start_reg <= 1'b1;
        end else if ((grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_ap_ready == 1'b1)) begin
            grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_ap_start_reg <= 1'b1;
        end else if ((grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_ap_ready == 1'b1)) begin
            grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_ap_start_reg <= 1'b1;
        end else if ((grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_ap_ready == 1'b1)) begin
            grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_fft_fu_175_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state10))) begin
            grp_fft_fu_175_ap_start_reg <= 1'b1;
        end else if ((grp_fft_fu_175_ap_ready == 1'b1)) begin
            grp_fft_fu_175_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_lshr_f6_cast_reg_268 <= {{grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_count_out[10:1]}};
        trunc_ln98_reg_274 <= trunc_ln98_fu_244_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        sub_reg_279 <= sub_fu_253_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_fft_fu_175_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_fft_fu_175_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_im_V_address0 = zext_ln98_fu_248_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_im_V_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_im_V_address0 = grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_im_V_address0;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5))) begin
        buf_im_V_address0 = grp_fft_fu_175_buf_im_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_im_V_address0 = grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_im_V_address0;
    end else begin
        buf_im_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        buf_im_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_im_V_ce0 = grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_im_V_ce0;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5))) begin
        buf_im_V_ce0 = grp_fft_fu_175_buf_im_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_im_V_ce0 = grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_im_V_ce0;
    end else begin
        buf_im_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5))) begin
        buf_im_V_ce1 = grp_fft_fu_175_buf_im_ce1;
    end else begin
        buf_im_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        buf_im_V_d0 = 40'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_im_V_d0 = grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_im_V_d0;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5))) begin
        buf_im_V_d0 = grp_fft_fu_175_buf_im_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_im_V_d0 = grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_im_V_d0;
    end else begin
        buf_im_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        buf_im_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_im_V_we0 = grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_im_V_we0;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5))) begin
        buf_im_V_we0 = grp_fft_fu_175_buf_im_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_im_V_we0 = grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_im_V_we0;
    end else begin
        buf_im_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_re_V_address0 = zext_ln98_fu_248_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_re_V_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        buf_re_V_address0 = grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_buf_re_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_re_V_address0 = grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_re_V_address0;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5))) begin
        buf_re_V_address0 = grp_fft_fu_175_buf_re_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_re_V_address0 = grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_re_V_address0;
    end else begin
        buf_re_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        buf_re_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        buf_re_V_ce0 = grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_buf_re_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_re_V_ce0 = grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_re_V_ce0;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5))) begin
        buf_re_V_ce0 = grp_fft_fu_175_buf_re_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_re_V_ce0 = grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_re_V_ce0;
    end else begin
        buf_re_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5))) begin
        buf_re_V_ce1 = grp_fft_fu_175_buf_re_ce1;
    end else begin
        buf_re_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        buf_re_V_d0 = 40'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_re_V_d0 = grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_re_V_d0;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5))) begin
        buf_re_V_d0 = grp_fft_fu_175_buf_re_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_re_V_d0 = grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_re_V_d0;
    end else begin
        buf_re_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        buf_re_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_re_V_we0 = grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_buf_re_V_we0;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5))) begin
        buf_re_V_we0 = grp_fft_fu_175_buf_re_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_re_V_we0 = grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_buf_re_V_we0;
    end else begin
        buf_re_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fft_fu_175_inverse_offset = 1'd1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fft_fu_175_inverse_offset = 1'd0;
    end else begin
        grp_fft_fu_175_inverse_offset = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_stream_TREADY_int_regslice = grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_fft_fu_175_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (grp_fft_fu_175_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_ap_start = grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_ap_start_reg;

assign grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_ap_start = grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_ap_start_reg;

assign grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TREADY = (out_stream_TREADY_int_regslice & ap_CS_fsm_state13);

assign grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_ap_start = grp_EQ_Pipeline_VITIS_LOOP_98_1_fu_201_ap_start_reg;

assign grp_fft_fu_175_ap_start = grp_fft_fu_175_ap_start_reg;

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign out_stream_TVALID_int_regslice = grp_EQ_Pipeline_VITIS_LOOP_187_2_fu_209_out_stream_TVALID;

assign sub_fu_253_p2 = ($signed(grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_count_out) + $signed(11'd2047));

assign trunc_ln98_fu_244_p1 = grp_EQ_Pipeline_VITIS_LOOP_165_1_fu_154_count_out[9:0];

assign zext_ln98_fu_248_p1 = p_lshr_f6_cast_reg_268;

endmodule //EQ
